name: Pull Request
on:
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCH: amd64
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-pr-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-buildx-pr

      - name: Build binaries
        run: |
          make multi-arch-build \
            CACHE_ARGS="--cache-from=type=local,src=${{ runner.temp }}/.buildx-cache --cache-to=type=local,dest=${{ runner.temp }}/.buildx-cache-new,compression=zstd,mode=max"

      - name: Move cache
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache