name: Test Databases
on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Kine
      run: DOCKER_BUILDKIT=1 make
    - name: Save Docker Images
      run: docker save rancher/kine | gzip > docker.tar.gz
    - name: Upload Kine Image
      uses: actions/upload-artifact@v3
      with:
        name: docker.${{ github.sha }}.tar.gz
        path: docker.tar.gz
        retention-days: 3
  
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Go Tests
      run: |
        . ./scripts/test-helpers
        go test -cover -tags=test ./...

  db-test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, mysql, cockroachdb, postgres, nats, nats-embedded, nats-socket]
      max-parallel: 3
    steps:
    - uses: actions/checkout@v4
    - name: Download Kine Image
      uses: actions/download-artifact@v3
      with:
        name: docker.${{ github.sha }}.tar.gz
    - name: Load images from cache
      run: gzip -dc docker.tar.gz | docker load
    - name: Install python dependencies
      run: pip install kubernetes termplotlib==v0.3.9
    - name: Run ${{ matrix.db }} Tests
      run: |
        . ./scripts/test-helpers
        . ./scripts/test-run-${{ matrix.db }}